In [1]:
#this is using the swcarpentry practice python w inflammation data

In [5]:
#Slicing Practice
element = 'oxygen'
print(element)
print('first three characters ([0:3]):', element[0:3])
print('Last character, eg [-1] : ', element[-1])

oxygen
first three characters ([0:3]): oxy
Last character, eg [-1] :  n


In [13]:
#writing a program to get a slice of the last three characters of an element, of any word
test_string = input("Enter a word ")
print(test_string)
last_three = test_string[(len(test_string)-3): len(test_string)]
print(last_three)
print(test_string[3:3])


Enter a word  carpentry


carpentry
try



In [39]:
#stacking arrays
import numpy
A = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print('A = ')
print(A)

B = numpy.hstack([A,A])
print('B = ')
print(B)

C = numpy.vstack([A,A])
print('C = ')
print(C)
print()
print()
shape_A = A.shape
print('A shape =', shape_A)
D = A[0:shape_A[0], :1]
print(D)
E = A[:, -1:]
print(E)
F = numpy.hstack([D,E])
print(F)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


A shape = (3, 3)
[[1]
 [4]
 [7]]
[[3]
 [6]
 [9]]
[[1 3]
 [4 6]
 [7 9]]


In [56]:
import numpy
import os 

filename = r'C:\Users\bowri\square1\python-novice-inflammation\data\inflammation-01.csv'
data = numpy.loadtxt(filename, delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
